//
//  Marshal.m
//  PlaynomicsUnityPlugin
//
//  Created by Jared Jenkins on 6/27/13.
//  Copyright (c) 2013 Jared Jenkins. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "Marshal.h"

// Converts NSString to C style string by way of copy (Mono will free it)

NSString* getPlaynomicsId()
{
    UIPasteboard *pasteBoard = [UIPasteboard pasteboardWithName:@"com.playnomics.uniqueDeviceId" create:YES];
    pasteBoard.persistent = YES;
    NSString *storedUUID = [pasteBoard string];
    if ([storedUUID length] == 0) {
        CFUUIDRef uuidRef = CFUUIDCreate(kCFAllocatorDefault);
        storedUUID = [(NSString *) CFUUIDCreateString(NULL, uuidRef) autorelease];
        CFRelease(uuidRef);
        pasteBoard.string = storedUUID;
    }
    return storedUUID;
}

const char * _playnomicsAutoGeneratedId()
{
	return makeStringCopy( getPlaynomicsId() );
}